### ISSUE TITLE
Move icon below Ruler in the Basic Control list

### ISSUE THREAD

**Issue by apoapostolov** [mothringer/foundry-vtt-pathfinding-ruler#2]
The icon is currently sorted at the bottom, would make more sense if it were second to the normal Ruler.

**Comment by mothringer** [comment]
This can't be accomplished as far as I can tell without reimplementing the entire base foundry function for populating the tools list, which would create extra maintenance work as foundry updates, as well as increased chance of incompatibility with other modules.
